Sinatra(DBなし)提出
maeda-seina/sinatra_kai pull request #1
Opened 2021-03-20 08:40 UTC by maeda-seina

添削お願いします！

2021-03-24 04:09 UTC, komagata requested changes

2021-03-24 04:09 UTC, komagata commented on main.rb
> +enable :method_override
これはクラシックスタイル（この書き方）だと最初から`enable`だったと思います〜

2021-03-24 04:09 UTC, komagata commented on main.rb
> +  @memo = JSON.parse(File.read("memos/#{params[:id]}.json"), symbolize_names: true)
これが複数回出てきているので共通化できるといいかもですね。

2021-03-24 12:19 UTC, maeda-seina commented on main.rb
> +  @memo = JSON.parse(File.read("memos/#{params[:id]}.json"), symbolize_names: true)
了解です！

2021-03-24 12:20 UTC, maeda-seina commented on main.rb
> +enable :method_override
了解いたしました！
削除します！

2021-03-25 03:39 UTC, komagata approved these changes
確認しました、OKですー🙆‍♂️

2021-03-25 03:48 UTC, merged